In [229]:
import pandas as pd
data = pd.read_csv("documents/BYMA.BA.csv")
data.tail()

           Date   Open   High    Low  Close  Adj Close  Volume
848  2020-12-17  600.0  607.0  593.0  605.5      605.5   43857
849  2020-12-18  606.0  615.0  600.0  611.0      611.0   18508
850  2020-12-21  595.0  603.0  595.0  600.0      600.0   28628
851  2020-12-22  591.0  615.0  591.0  609.5      609.5   16772
852  2020-12-23  610.0  626.0  592.5  624.0      624.0   29991

In [230]:
#mg_hi = na(mg_hi[1]) ? ema(high, length) : mg_hi[1] + (high - mg_hi[1]) / (length * pow(high/mg_hi[1], 4))

In [231]:
data['MG_HI']=data['High']
data['MG_LO']=data['Low']
data.tail()

           Date   Open   High    Low  Close  Adj Close  Volume  MG_HI  MG_LO
848  2020-12-17  600.0  607.0  593.0  605.5      605.5   43857  607.0  593.0
849  2020-12-18  606.0  615.0  600.0  611.0      611.0   18508  615.0  600.0
850  2020-12-21  595.0  603.0  595.0  600.0      600.0   28628  603.0  595.0
851  2020-12-22  591.0  615.0  591.0  609.5      609.5   16772  615.0  591.0
852  2020-12-23  610.0  626.0  592.5  624.0      624.0   29991  626.0  592.5

In [232]:
#for i in range(1, len(df)):
#    df.loc[i, 'C'] = df.loc[i-1, 'C'] * df.loc[i, 'A'] + df.loc[i, 'B']
for i in range(1, len(data)):
    data.loc[i,'MG_HI'] = data.loc[i-1,'MG_HI'] + (data.loc[i,'High']-data.loc[i-1,'MG_HI']) / (6*pow(data.loc[i,'High']/data.loc[i-1,'MG_HI'], 4))
    data.loc[i,'MG_LO'] = data.loc[i-1,'MG_LO'] + (data.loc[i,'Low']-data.loc[i-1,'MG_LO']) / (6*max(pow(data.loc[i,'Low']/data.loc[i-1,'MG_LO'], 4),0.3))

In [233]:
data.tail()

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO
848,2020-12-17,600.0,607.0,593.0,605.5,605.5,43857,607.847469,589.606969
849,2020-12-18,606.0,615.0,600.0,611.0,611.0,18508,608.985061,591.222207
850,2020-12-21,595.0,603.0,595.0,600.0,600.0,28628,607.947354,591.836000
851,2020-12-22,591.0,615.0,591.0,609.5,609.5,16772,609.069797,591.695877
852,2020-12-23,610.0,626.0,592.5,624.0,624.0,29991,611.598407,591.829171

In [234]:
data['MG_HI']=data['MG_HI'].shift(4).ffill()
data['MG_LO']=data['MG_LO'].shift(4).ffill()

In [235]:
data

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO
0,2017-06-26,150.5,150.5,149.100006,149.699997,145.079773,93495,NaN,NaN
1,2017-06-27,149.5,151.0,149.000000,150.000000,145.370514,104046,NaN,NaN
2,2017-06-28,150.0,150.0,149.000000,149.149994,144.546753,91852,NaN,NaN
3,2017-06-29,150.0,150.0,147.000000,147.000000,142.463104,56476,NaN,NaN
4,2017-06-30,147.0,148.0,144.500000,145.500000,141.009399,56810,150.500000,149.100006
...,...,...,...,...,...,...,...,...,...
848,2020-12-17,600.0,607.0,593.000000,605.500000,605.500000,43857,609.506529,585.871679
849,2020-12-18,606.0,615.0,600.000000,611.000000,611.000000,18508,608.644119,587.003629
850,2020-12-21,595.0,603.0,595.000000,600.000000,600.000000,28628,608.022000,587.808599
851,2020-12-22,591.0,615.0,591.000000,609.500000,609.500000,16772,608.018333,588.950263
852,2020-12-23,610.0,626.0,592.500000,624.000000,624.000000,29991,607.847469,589.606969

In [236]:
data = data.iloc[4:]

In [237]:
data.reset_index(inplace=True,drop=True)

In [238]:
data

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO
0,2017-06-30,147.000000,148.0,144.500000,145.500000,141.009399,56810,150.500000,149.100006
1,2017-07-03,145.000000,145.0,139.000000,141.800003,137.423599,82552,150.582235,149.083294
2,2017-07-04,142.300003,144.0,139.500000,139.600006,135.291504,32539,150.483680,149.069380
3,2017-07-05,140.000000,141.0,139.199997,139.300003,135.000763,82570,150.402022,148.704649
4,2017-07-06,139.350006,140.0,134.250000,135.449997,131.269577,30111,149.975056,147.918680
...,...,...,...,...,...,...,...,...,...
844,2020-12-17,600.000000,607.0,593.000000,605.500000,605.500000,43857,609.506529,585.871679
845,2020-12-18,606.000000,615.0,600.000000,611.000000,611.000000,18508,608.644119,587.003629
846,2020-12-21,595.000000,603.0,595.000000,600.000000,600.000000,28628,608.022000,587.808599
847,2020-12-22,591.000000,615.0,591.000000,609.500000,609.500000,16772,608.018333,588.950263
848,2020-12-23,610.000000,626.0,592.500000,624.000000,624.000000,29991,607.847469,589.606969

In [240]:
data['signal']=" "
for i in range (1,len(data)):
    if (data.loc[i,'Close']>data.loc[i,'MG_HI'] and data.loc[i-1,'Close']<data.loc[i-1,'MG_HI']):
        data.loc[i,'signal']="BUY"
    if (data.loc[i,'Close']<data.loc[i,'MG_LO'] and data.loc[i-1,'Close']>data.loc[i-1,'MG_LO']):
        data.loc[i,'signal']="SELL"

<ipython-input-240-7847fc268876>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['signal']=" "

In [241]:
data

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO,signal
0,2017-06-30,147.000000,148.0,144.500000,145.500000,141.009399,56810,150.500000,149.100006,
1,2017-07-03,145.000000,145.0,139.000000,141.800003,137.423599,82552,150.582235,149.083294,
2,2017-07-04,142.300003,144.0,139.500000,139.600006,135.291504,32539,150.483680,149.069380,
3,2017-07-05,140.000000,141.0,139.199997,139.300003,135.000763,82570,150.402022,148.704649,
4,2017-07-06,139.350006,140.0,134.250000,135.449997,131.269577,30111,149.975056,147.918680,
...,...,...,...,...,...,...,...,...,...,...
844,2020-12-17,600.000000,607.0,593.000000,605.500000,605.500000,43857,609.506529,585.871679,
845,2020-12-18,606.000000,615.0,600.000000,611.000000,611.000000,18508,608.644119,587.003629,BUY
846,2020-12-21,595.000000,603.0,595.000000,600.000000,600.000000,28628,608.022000,587.808599,
847,2020-12-22,591.000000,615.0,591.000000,609.500000,609.500000,16772,608.018333,588.950263,BUY
848,2020-12-23,610.000000,626.0,592.500000,624.000000,624.000000,29991,607.847469,589.606969,

In [246]:
trading=pd.DataFrame()
trading=data[(data['signal']=="SELL") | (data['signal']=="BUY")]
trading

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO,signal
12,2017-07-18,139.000000,142.000000,138.000000,138.000000,133.740875,86166,137.653745,134.530697,BUY
18,2017-07-26,140.000000,141.399994,138.500000,140.000000,135.679153,45983,139.521727,135.391691,BUY
25,2017-08-04,140.949997,142.000000,139.500000,141.000000,136.648285,88709,140.731684,138.293610,BUY
28,2017-08-09,141.899994,141.899994,134.199997,135.000000,130.833466,144865,140.955261,138.810568,SELL
31,2017-08-14,143.500000,144.899994,140.100006,141.800003,137.423599,78553,141.515808,139.080975,BUY
...,...,...,...,...,...,...,...,...,...,...
811,2020-10-28,529.000000,530.000000,485.000000,499.500000,499.500000,59790,545.741807,521.046616,SELL
815,2020-11-03,547.000000,564.000000,540.000000,557.500000,557.500000,69699,548.285852,514.342323,BUY
817,2020-11-05,540.000000,559.500000,533.000000,556.500000,556.500000,41982,540.358544,510.323903,BUY
845,2020-12-18,606.000000,615.000000,600.000000,611.000000,611.000000,18508,608.644119,587.003629,BUY
847,2020-12-22,591.000000,615.000000,591.000000,609.500000,609.500000,16772,608.018333,588.950263,BUY

In [247]:
trading.reset_index(drop=True,inplace=True)
trading

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO,signal
0,2017-07-18,139.000000,142.000000,138.000000,138.000000,133.740875,86166,137.653745,134.530697,BUY
1,2017-07-26,140.000000,141.399994,138.500000,140.000000,135.679153,45983,139.521727,135.391691,BUY
2,2017-08-04,140.949997,142.000000,139.500000,141.000000,136.648285,88709,140.731684,138.293610,BUY
3,2017-08-09,141.899994,141.899994,134.199997,135.000000,130.833466,144865,140.955261,138.810568,SELL
4,2017-08-14,143.500000,144.899994,140.100006,141.800003,137.423599,78553,141.515808,139.080975,BUY
...,...,...,...,...,...,...,...,...,...,...
80,2020-10-28,529.000000,530.000000,485.000000,499.500000,499.500000,59790,545.741807,521.046616,SELL
81,2020-11-03,547.000000,564.000000,540.000000,557.500000,557.500000,69699,548.285852,514.342323,BUY
82,2020-11-05,540.000000,559.500000,533.000000,556.500000,556.500000,41982,540.358544,510.323903,BUY
83,2020-12-18,606.000000,615.000000,600.000000,611.000000,611.000000,18508,608.644119,587.003629,BUY
84,2020-12-22,591.000000,615.000000,591.000000,609.500000,609.500000,16772,608.018333,588.950263,BUY

In [248]:
trading['control']=' '
for i in range (1,len(trading)):
    if (trading.loc[i,'signal']==trading.loc[i-1,'signal']):
        trading.loc[i,'control']="delete"
trading

<ipython-input-248-547ff2d44bce>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trading['control']=' '
K:\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO,signal,control
0,2017-07-18,139.000000,142.000000,138.000000,138.000000,133.740875,86166,137.653745,134.530697,BUY,
1,2017-07-26,140.000000,141.399994,138.500000,140.000000,135.679153,45983,139.521727,135.391691,BUY,delete
2,2017-08-04,140.949997,142.000000,139.500000,141.000000,136.648285,88709,140.731684,138.293610,BUY,delete
3,2017-08-09,141.899994,141.899994,134.199997,135.000000,130.833466,144865,140.955261,138.810568,SELL,
4,2017-08-14,143.500000,144.899994,140.100006,141.800003,137.423599,78553,141.515808,139.080975,BUY,
...,...,...,...,...,...,...,...,...,...,...,...
80,2020-10-28,529.000000,530.000000,485.000000,499.500000,499.500000,59790,545.741807,521.046616,SELL,
81,2020-11-03,547.000000,564.000000,540.000000,557.500000,557.500000,69699,548.285852,514.342323,BUY,
82,2020-11-05,540.000000,559.500000,533.000000,556.500000,556.500000,41982,540.358544,510.323903,BUY,delete
83,2020-12-18,606.000000,615.000000,600.000000,611.000000,611.000000,18508,608.644119,587.003629,BUY,delete
84,2020-12-22,591.000000,615.000000,591.000000,609.500000,609.500000,16772,608.018333,588.950263,BUY,delete

In [249]:
trading.drop(trading[trading['control']=="delete"].index,axis=0,inplace=True)
trading

K:\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO,signal,control
0,2017-07-18,139.000000,142.000000,138.000000,138.000000,133.740875,86166,137.653745,134.530697,BUY,
3,2017-08-09,141.899994,141.899994,134.199997,135.000000,130.833466,144865,140.955261,138.810568,SELL,
4,2017-08-14,143.500000,144.899994,140.100006,141.800003,137.423599,78553,141.515808,139.080975,BUY,
5,2017-08-29,138.199997,138.199997,136.149994,138.000000,133.740875,11939,140.825154,138.220388,SELL,
6,2017-09-01,139.300003,141.500000,138.899994,141.250000,136.890579,107330,140.860664,138.455438,BUY,
10,2018-02-05,336.000000,338.450012,314.799988,329.500000,319.330597,160664,344.438055,331.493382,SELL,
11,2018-02-26,321.000000,355.000000,321.000000,348.700012,337.938019,348710,331.409017,317.799743,BUY,
12,2018-04-16,402.000000,403.000000,384.000000,390.350006,379.759888,92957,408.400711,396.996206,SELL,
13,2018-05-16,352.000000,383.000000,352.000000,380.799988,370.468964,139820,354.100209,318.898800,BUY,
14,2018-05-24,341.500000,342.000000,328.500000,330.549988,321.582214,86389,363.770604,335.468602,SELL,
15,2018-06-04,349.149994,374.950012,349.149994,374.200012,364.048035,294041,351.665912,328.915381,BUY,
16,2018-06-18,346.000000,346.000000,306.000000,314.700012,306.162262,316103,375.741138,354.833181,SELL,
17,2018-06-21,387.000000,414.549988,387.000000,399.850006,389.002167,649967,376.752457,355.701645,BUY,
18,2018-06-29,353.000000,353.000000,320.000000,344.799988,335.445648,309301,375.417570,348.447327,SELL,
19,2018-07-05,374.000000,381.000000,365.000000,380.049988,369.739288,90259,368.902855,340.840473,BUY,
20,2018-07-19,360.000000,362.000000,354.000000,355.299988,345.660767,20666,376.088690,355.435340,SELL,
21,2018-07-25,370.000000,384.000000,367.899994,379.799988,369.496094,99827,371.689363,356.446625,BUY,
22,2018-08-07,375.000000,375.000000,360.000000,365.250000,355.340851,38194,381.942674,369.515038,SELL,
23,2018-08-16,375.200012,380.000000,365.000000,375.799988,365.604614,83408,372.127318,348.479422,BUY,
24,2018-08-24,359.000000,359.500000,325.000000,345.299988,335.932068,419854,372.852705,353.046137,SELL,
25,2018-08-31,331.000000,375.000000,328.700012,370.299988,360.253815,145811,366.235018,344.756271,BUY,
27,2018-09-12,342.000000,342.000000,330.000000,331.049988,322.068665,85081,356.075496,332.021997,SELL,
28,2018-09-19,344.000000,372.000000,344.000000,368.700012,358.697266,214146,348.207418,330.655529,BUY,
29,2018-10-05,360.000000,367.200012,338.000000,345.649994,336.272583,170623,369.171292,352.339139,SELL,
33,2018-11-02,350.000000,352.500000,345.500000,352.100006,342.547607,56620,348.582135,336.798322,BUY,
34,2018-11-23,358.000000,358.000000,355.000000,355.049988,345.417542,36357,369.209147,355.929007,SELL,
35,2018-12-03,363.100006,371.000000,363.000000,367.200012,357.237946,152097,362.200702,349.901101,BUY,
36,2018-12-18,354.000000,354.000000,341.000000,343.950012,334.618744,127360,365.652686,353.826296,SELL,
37,2018-12-28,351.000000,380.000000,340.000000,378.399994,368.134064,133830,358.134347,345.472362,BUY,
41,2019-02-20,377.000000,383.500000,365.000000,366.500000,356.556915,218048,386.558052,377.934174,SELL,
42,2019-05-02,290.000000,299.000000,287.000000,293.500000,290.393463,46689,292.781711,275.432425,BUY,
43,2019-05-22,302.500000,302.500000,286.000000,287.500000,284.456970,47840,301.208659,289.260138,SELL,
44,2019-06-07,270.000000,292.000000,270.000000,290.500000,287.425232,418371,280.620780,269.047800,BUY,
45,2019-07-16,340.000000,344.500000,331.000000,332.000000,328.485962,54815,356.236424,342.169848,SELL,
46,2019-07-25,340.000000,342.000000,330.000000,342.000000,338.380127,66823,341.888039,328.177505,BUY,
47,2019-08-12,249.000000,249.000000,185.500000,200.250000,198.130478,728015,360.162513,346.370656,SELL,
49,2019-09-05,216.000000,225.500000,214.000000,221.500000,219.155548,178547,218.865617,204.667742,BUY,
54,2019-10-22,219.000000,221.000000,212.500000,213.250000,210.992874,103379,224.085979,218.384297,SELL,
56,2019-10-29,209.000000,226.000000,208.000000,226.000000,223.607925,167858,222.945349,216.490970,BUY,
57,2019-11-14,252.000000,270.000000,234.000000,238.000000,235.480911,70711,255.245889,239.909763,SELL,
59,2019-12-03,245.000000,261.000000,245.000000,259.500000,256.753357,17823,256.488594,241.134321,BUY,
60,2020-01-14,300.000000,300.000000,290.000000,292.500000,289.404053,53666,307.978499,294.365361,SELL,
61,2020-01-21,305.000000,310.000000,301.000000,305.500000,302.266449,98531,305.194719,293.047976,BUY,
62,2020-01-24,300.000000,302.000000,290.000000,293.000000,289.898773,40863,305.101051,294.903531,SELL,
63,2020-02-12,275.000000,293.000000,270.500000,290.000000,286.930511,308562,279.421748,269.254389,BUY,
66,2020-03-09,270.000000,277.000000,260.000000,268.500000,265.658081,139062,296.060193,280.848441,SELL,
67,2020-04-13,236.500000,257.500000,228.000000,255.000000,255.000000,231283,245.904797,232.695589,BUY,
70,2020-07-03,383.000000,388.000000,370.000000,375.500000,375.500000,24392,394.076266,379.053622,SELL,
71,2020-07-06,384.500000,423.500000,384.500000,405.000000,405.000000,189254,394.063545,377.391485,BUY,
72,2020-08-20,492.000000,494.000000,476.000000,483.000000,483.000000,92164,507.333947,483.738649,SELL,
73,2020-08-25,503.500000,524.000000,485.000000,515.500000,515.500000,46300,501.653586,479.279298,BUY,
74,2020-09-16,573.000000,573.000000,533.000000,537.000000,537.000000,75162,564.408360,537.763230,SELL,
75,2020-09-29,540.000000,545.000000,475.000000,526.500000,526.500000,31146,525.340927,492.101690,BUY,
80,2020-10-28,529.000000,530.000000,485.000000,499.500000,499.500000,59790,545.741807,521.046616,SELL,
81,2020-11-03,547.000000,564.000000,540.000000,557.500000,557.500000,69699,548.285852,514.342323,BUY,

In [252]:
trading.reset_index(drop=True,inplace=True)
trading.drop(columns='control',inplace=True)
trading

K:\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO,signal
0,2017-07-18,139.000000,142.000000,138.000000,138.000000,133.740875,86166,137.653745,134.530697,BUY
1,2017-08-09,141.899994,141.899994,134.199997,135.000000,130.833466,144865,140.955261,138.810568,SELL
2,2017-08-14,143.500000,144.899994,140.100006,141.800003,137.423599,78553,141.515808,139.080975,BUY
3,2017-08-29,138.199997,138.199997,136.149994,138.000000,133.740875,11939,140.825154,138.220388,SELL
4,2017-09-01,139.300003,141.500000,138.899994,141.250000,136.890579,107330,140.860664,138.455438,BUY
5,2018-02-05,336.000000,338.450012,314.799988,329.500000,319.330597,160664,344.438055,331.493382,SELL
6,2018-02-26,321.000000,355.000000,321.000000,348.700012,337.938019,348710,331.409017,317.799743,BUY
7,2018-04-16,402.000000,403.000000,384.000000,390.350006,379.759888,92957,408.400711,396.996206,SELL
8,2018-05-16,352.000000,383.000000,352.000000,380.799988,370.468964,139820,354.100209,318.898800,BUY
9,2018-05-24,341.500000,342.000000,328.500000,330.549988,321.582214,86389,363.770604,335.468602,SELL
10,2018-06-04,349.149994,374.950012,349.149994,374.200012,364.048035,294041,351.665912,328.915381,BUY
11,2018-06-18,346.000000,346.000000,306.000000,314.700012,306.162262,316103,375.741138,354.833181,SELL
12,2018-06-21,387.000000,414.549988,387.000000,399.850006,389.002167,649967,376.752457,355.701645,BUY
13,2018-06-29,353.000000,353.000000,320.000000,344.799988,335.445648,309301,375.417570,348.447327,SELL
14,2018-07-05,374.000000,381.000000,365.000000,380.049988,369.739288,90259,368.902855,340.840473,BUY
15,2018-07-19,360.000000,362.000000,354.000000,355.299988,345.660767,20666,376.088690,355.435340,SELL
16,2018-07-25,370.000000,384.000000,367.899994,379.799988,369.496094,99827,371.689363,356.446625,BUY
17,2018-08-07,375.000000,375.000000,360.000000,365.250000,355.340851,38194,381.942674,369.515038,SELL
18,2018-08-16,375.200012,380.000000,365.000000,375.799988,365.604614,83408,372.127318,348.479422,BUY
19,2018-08-24,359.000000,359.500000,325.000000,345.299988,335.932068,419854,372.852705,353.046137,SELL
20,2018-08-31,331.000000,375.000000,328.700012,370.299988,360.253815,145811,366.235018,344.756271,BUY
21,2018-09-12,342.000000,342.000000,330.000000,331.049988,322.068665,85081,356.075496,332.021997,SELL
22,2018-09-19,344.000000,372.000000,344.000000,368.700012,358.697266,214146,348.207418,330.655529,BUY
23,2018-10-05,360.000000,367.200012,338.000000,345.649994,336.272583,170623,369.171292,352.339139,SELL
24,2018-11-02,350.000000,352.500000,345.500000,352.100006,342.547607,56620,348.582135,336.798322,BUY
25,2018-11-23,358.000000,358.000000,355.000000,355.049988,345.417542,36357,369.209147,355.929007,SELL
26,2018-12-03,363.100006,371.000000,363.000000,367.200012,357.237946,152097,362.200702,349.901101,BUY
27,2018-12-18,354.000000,354.000000,341.000000,343.950012,334.618744,127360,365.652686,353.826296,SELL
28,2018-12-28,351.000000,380.000000,340.000000,378.399994,368.134064,133830,358.134347,345.472362,BUY
29,2019-02-20,377.000000,383.500000,365.000000,366.500000,356.556915,218048,386.558052,377.934174,SELL
30,2019-05-02,290.000000,299.000000,287.000000,293.500000,290.393463,46689,292.781711,275.432425,BUY
31,2019-05-22,302.500000,302.500000,286.000000,287.500000,284.456970,47840,301.208659,289.260138,SELL
32,2019-06-07,270.000000,292.000000,270.000000,290.500000,287.425232,418371,280.620780,269.047800,BUY
33,2019-07-16,340.000000,344.500000,331.000000,332.000000,328.485962,54815,356.236424,342.169848,SELL
34,2019-07-25,340.000000,342.000000,330.000000,342.000000,338.380127,66823,341.888039,328.177505,BUY
35,2019-08-12,249.000000,249.000000,185.500000,200.250000,198.130478,728015,360.162513,346.370656,SELL
36,2019-09-05,216.000000,225.500000,214.000000,221.500000,219.155548,178547,218.865617,204.667742,BUY
37,2019-10-22,219.000000,221.000000,212.500000,213.250000,210.992874,103379,224.085979,218.384297,SELL
38,2019-10-29,209.000000,226.000000,208.000000,226.000000,223.607925,167858,222.945349,216.490970,BUY
39,2019-11-14,252.000000,270.000000,234.000000,238.000000,235.480911,70711,255.245889,239.909763,SELL
40,2019-12-03,245.000000,261.000000,245.000000,259.500000,256.753357,17823,256.488594,241.134321,BUY
41,2020-01-14,300.000000,300.000000,290.000000,292.500000,289.404053,53666,307.978499,294.365361,SELL
42,2020-01-21,305.000000,310.000000,301.000000,305.500000,302.266449,98531,305.194719,293.047976,BUY
43,2020-01-24,300.000000,302.000000,290.000000,293.000000,289.898773,40863,305.101051,294.903531,SELL
44,2020-02-12,275.000000,293.000000,270.500000,290.000000,286.930511,308562,279.421748,269.254389,BUY
45,2020-03-09,270.000000,277.000000,260.000000,268.500000,265.658081,139062,296.060193,280.848441,SELL
46,2020-04-13,236.500000,257.500000,228.000000,255.000000,255.000000,231283,245.904797,232.695589,BUY
47,2020-07-03,383.000000,388.000000,370.000000,375.500000,375.500000,24392,394.076266,379.053622,SELL
48,2020-07-06,384.500000,423.500000,384.500000,405.000000,405.000000,189254,394.063545,377.391485,BUY
49,2020-08-20,492.000000,494.000000,476.000000,483.000000,483.000000,92164,507.333947,483.738649,SELL
50,2020-08-25,503.500000,524.000000,485.000000,515.500000,515.500000,46300,501.653586,479.279298,BUY
51,2020-09-16,573.000000,573.000000,533.000000,537.000000,537.000000,75162,564.408360,537.763230,SELL
52,2020-09-29,540.000000,545.000000,475.000000,526.500000,526.500000,31146,525.340927,492.101690,BUY
53,2020-10-28,529.000000,530.000000,485.000000,499.500000,499.500000,59790,545.741807,521.046616,SELL
54,2020-11-03,547.000000,564.000000,540.000000,557.500000,557.500000,69699,548.285852,514.342323,BUY

In [253]:
trading['cum']=0
for i in range(0,len(trading)):
    if(i == 0 ):
         trading.loc[i,'cum']= trading.loc[i,'Close'] if(trading.loc[i,'signal']=="SELL") else trading.loc[i,'Close']*-1
    else:
        trading.loc[i,'cum']=trading.loc[i-1,'cum']-trading.loc[i,'Close'] if(trading.loc[i,'signal']=="BUY") else trading.loc[i-1,'cum']+trading.loc[i,'Close']

<ipython-input-253-b83ab335477c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trading['cum']=0
K:\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [225]:
trading

,Date,Open,High,Low,Close,Adj Close,Volume,MG_HI,MG_LO,signal,cum
0,2017-07-18,139.000000,142.000000,138.000000,138.000000,133.740875,86166,137.653745,134.530697,BUY,-138.000000
1,2017-08-09,141.899994,141.899994,134.199997,135.000000,130.833466,144865,140.955261,138.810568,SELL,-3.000000
2,2017-08-14,143.500000,144.899994,140.100006,141.800003,137.423599,78553,141.515808,139.080975,BUY,-144.800003
3,2017-08-29,138.199997,138.199997,136.149994,138.000000,133.740875,11939,140.825154,138.220388,SELL,-6.800003
4,2017-09-01,139.300003,141.500000,138.899994,141.250000,136.890579,107330,140.860664,138.455438,BUY,-148.050003
5,2018-02-05,336.000000,338.450012,314.799988,329.500000,319.330597,160664,344.438055,331.493382,SELL,181.449997
6,2018-02-26,321.000000,355.000000,321.000000,348.700012,337.938019,348710,331.409017,317.799743,BUY,-167.250015
7,2018-04-16,402.000000,403.000000,384.000000,390.350006,379.759888,92957,408.400711,396.996206,SELL,223.099991
8,2018-05-16,352.000000,383.000000,352.000000,380.799988,370.468964,139820,354.100209,318.898800,BUY,-157.699997
9,2018-05-24,341.500000,342.000000,328.500000,330.549988,321.582214,86389,363.770604,335.468602,SELL,172.849991
10,2018-06-04,349.149994,374.950012,349.149994,374.200012,364.048035,294041,351.665912,328.915381,BUY,-201.350021
11,2018-06-18,346.000000,346.000000,306.000000,314.700012,306.162262,316103,375.741138,354.833181,SELL,113.349991
12,2018-06-21,387.000000,414.549988,387.000000,399.850006,389.002167,649967,376.752457,355.701645,BUY,-286.500015
13,2018-06-29,353.000000,353.000000,320.000000,344.799988,335.445648,309301,375.417570,348.447327,SELL,58.299973
14,2018-07-05,374.000000,381.000000,365.000000,380.049988,369.739288,90259,368.902855,340.840473,BUY,-321.750015
15,2018-07-19,360.000000,362.000000,354.000000,355.299988,345.660767,20666,376.088690,355.435340,SELL,33.549973
16,2018-07-25,370.000000,384.000000,367.899994,379.799988,369.496094,99827,371.689363,356.446625,BUY,-346.250015
17,2018-08-07,375.000000,375.000000,360.000000,365.250000,355.340851,38194,381.942674,369.515038,SELL,18.999985
18,2018-08-16,375.200012,380.000000,365.000000,375.799988,365.604614,83408,372.127318,348.479422,BUY,-356.800003
19,2018-08-24,359.000000,359.500000,325.000000,345.299988,335.932068,419854,372.852705,353.046137,SELL,-11.500015
20,2018-08-31,331.000000,375.000000,328.700012,370.299988,360.253815,145811,366.235018,344.756271,BUY,-381.800003
21,2018-09-12,342.000000,342.000000,330.000000,331.049988,322.068665,85081,356.075496,332.021997,SELL,-50.750015
22,2018-09-19,344.000000,372.000000,344.000000,368.700012,358.697266,214146,348.207418,330.655529,BUY,-419.450027
23,2018-10-05,360.000000,367.200012,338.000000,345.649994,336.272583,170623,369.171292,352.339139,SELL,-73.800033
24,2018-11-02,350.000000,352.500000,345.500000,352.100006,342.547607,56620,348.582135,336.798322,BUY,-425.900039
25,2018-11-23,358.000000,358.000000,355.000000,355.049988,345.417542,36357,369.209147,355.929007,SELL,-70.850051
26,2018-12-03,363.100006,371.000000,363.000000,367.200012,357.237946,152097,362.200702,349.901101,BUY,-438.050063
27,2018-12-18,354.000000,354.000000,341.000000,343.950012,334.618744,127360,365.652686,353.826296,SELL,-94.100051
28,2018-12-28,351.000000,380.000000,340.000000,378.399994,368.134064,133830,358.134347,345.472362,BUY,-472.500045
29,2019-02-20,377.000000,383.500000,365.000000,366.500000,356.556915,218048,386.558052,377.934174,SELL,-106.000045
30,2019-05-02,290.000000,299.000000,287.000000,293.500000,290.393463,46689,292.781711,275.432425,BUY,-399.500045
31,2019-05-22,302.500000,302.500000,286.000000,287.500000,284.456970,47840,301.208659,289.260138,SELL,-112.000045
32,2019-06-07,270.000000,292.000000,270.000000,290.500000,287.425232,418371,280.620780,269.047800,BUY,-402.500045
33,2019-07-16,340.000000,344.500000,331.000000,332.000000,328.485962,54815,356.236424,342.169848,SELL,-70.500045
34,2019-07-25,340.000000,342.000000,330.000000,342.000000,338.380127,66823,341.888039,328.177505,BUY,-412.500045
35,2019-08-12,249.000000,249.000000,185.500000,200.250000,198.130478,728015,360.162513,346.370656,SELL,-212.250045
36,2019-09-05,216.000000,225.500000,214.000000,221.500000,219.155548,178547,218.865617,204.667742,BUY,-433.750045
37,2019-10-22,219.000000,221.000000,212.500000,213.250000,210.992874,103379,224.085979,218.384297,SELL,-220.500045
38,2019-10-29,209.000000,226.000000,208.000000,226.000000,223.607925,167858,222.945349,216.490970,BUY,-446.500045
39,2019-11-14,252.000000,270.000000,234.000000,238.000000,235.480911,70711,255.245889,239.909763,SELL,-208.500045
40,2019-12-03,245.000000,261.000000,245.000000,259.500000,256.753357,17823,256.488594,241.134321,BUY,-468.000045
41,2020-01-14,300.000000,300.000000,290.000000,292.500000,289.404053,53666,307.978499,294.365361,SELL,-175.500045
42,2020-01-21,305.000000,310.000000,301.000000,305.500000,302.266449,98531,305.194719,293.047976,BUY,-481.000045
43,2020-01-24,300.000000,302.000000,290.000000,293.000000,289.898773,40863,305.101051,294.903531,SELL,-188.000045
44,2020-02-12,275.000000,293.000000,270.500000,290.000000,286.930511,308562,279.421748,269.254389,BUY,-478.000045
45,2020-03-09,270.000000,277.000000,260.000000,268.500000,265.658081,139062,296.060193,280.848441,SELL,-209.500045
46,2020-04-13,236.500000,257.500000,228.000000,255.000000,255.000000,231283,245.904797,232.695589,BUY,-464.500045
47,2020-07-03,383.000000,388.000000,370.000000,375.500000,375.500000,24392,394.076266,379.053622,SELL,-89.000045
48,2020-07-06,384.500000,423.500000,384.500000,405.000000,405.000000,189254,394.063545,377.391485,BUY,-494.000045
49,2020-08-20,492.000000,494.000000,476.000000,483.000000,483.000000,92164,507.333947,483.738649,SELL,-11.000045
50,2020-08-25,503.500000,524.000000,485.000000,515.500000,515.500000,46300,501.653586,479.279298,BUY,-526.500045
51,2020-09-16,573.000000,573.000000,533.000000,537.000000,537.000000,75162,564.408360,537.763230,SELL,10.499955
52,2020-09-29,540.000000,545.000000,475.000000,526.500000,526.500000,31146,525.340927,492.101690,BUY,-516.000045
53,2020-10-28,529.000000,530.000000,485.000000,499.500000,499.500000,59790,545.741807,521.046616,SELL,-16.500045
54,2020-11-03,547.000000,564.000000,540.000000,557.500000,557.500000,69699,548.285852,514.342323,BUY,-574.000045

In [254]:
close=data.tail(1)['Close'].values[0]
cum=trading.tail(1)['cum'].values[0]
trading.tail(1)['signal']

54    BUY
Name: signal, dtype: object

In [255]:
total=0
if trading.tail(1)['signal'].values[0]=="BUY":
    total=data.tail(1)['Close'].values[0]+trading.tail(1)['cum'].values[0]
else:
    total=data.tail(1)['Close'].values[0]-trading.tail(1)['cum'].values[0]

In [256]:
total

49.999955

In [272]:
trading[trading['signal']=="SELL"].count(axis=0)[0]-trading[trading['cum']>0].count(axis=0)[0]

19